apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
        - name: flask-app
          image: smitkoli/product-service:latest
          ports:
            - containerPort: 5000